const DNA =
    "CCGTCCCTTCCCGTTACCGAGGGATTTGAGGCGACGATAAGGGGCTGGGTTGAAAGATTCTCACGAGGTTTGCCCCCAGAATTAGTGCGGCTGCTAATCGGTATCCAATCAGTCTCATCGCGCAGGCGTTCGTGGCTAACCGAAAACGTTAATAAGTGAAATCTGGAGGGACAACGATAGTTCGTCGGAAGTGCCGTGACGTTCCTCGGTTGTTAAGGCATCTCTATTACTTTACCGTAACATGACACAGGGAGCACAGTATCGTCAAAAACTGGCGATTAGGATTGTCTGGGGTCCGTGCGTAGCAGGCTCTGTTATAATCGCAGATGGGAGTGAGCTCTGTGTCTTGGTCGCCACTGATTATCAACGAATTACTTAGCACAGAATGGAGTATTTCTGTCCACCACACACAATTGTAGCAAAGTGTACCACAGAGGCGGACCGGTCTTTTTCATAACAATGCTATCCCCTGTCGTTATGTGATAAAGTTAGAGAATCTGCCCGCGATAGGGCCGCCGCAGAATTTTTCGGCACTCCAAGTCACTGCGGACGGTTCCTTGGGGTCCACTGACTGCTTGGGAGTTAGTCCGTCAGCGCCTGCTAATCCAGCCCCAAGCTTCGACCCAACCGTACCTAGACACGAACAGGCGCAATAATGCGATTAGTAGCTCACGCCGAGCGGTCATCTGAACAATCGCGACCGCCAGCCTATGGCCGCCCACTACACGCCCAGCCTTGTAACGCCATTCACTGTCTAGTTTTCGGACGTACCATTAGCTACTTTAACATGAACTCCGATGTGTACGGTTTTATGTTTGTATGGCGACACAGCCCGAACCGCAGGATGTCGTAAGTGATAGGCACAGATGAGAAAATTAGCAGGCTACAACCCTGCACACCCGTATTCTCTACTAGGAAAAAAGTTCGGGGACTATCGTCATCGAGGCGTGGTGGGCCGTTATCCA";

void reverseComplement(String dna) {
  String rcDNA = "";
  for (int i = dna.length - 1; i >= 0; i--) {
    switch (dna[i]) {
      case "A":
        rcDNA = rcDNA + "T";
        break;
      case "T":
        rcDNA = rcDNA + "A";
        break;
      case "C":
        rcDNA = rcDNA + "G";
        break;
      default:
        rcDNA = rcDNA + "C";
        break;
    }
  }
  print(rcDNA);
}

main() {
  reverseComplement(DNA);
}
